name: ubuntu

on:
  push:
    branches:
      - main
  pull_request:
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Compilation
        run: |
          cmake .
          make clean
          make
      - name: make.sh
        run: |
          make build
          make test
          make clean
